name: Development
on:
  push:
    branches:
      - develop

jobs:

  devtesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install numpy Cython scipy==1.8.1
          pip install -r tests/requirements.txt
      - name: Install pymoo
        run: |
          pip install .
          rm -rf pymoo
      - name: Run Tests
        run: |
          cd tests
          pytest -v --maxfail 1 --no-header -m "not long"
          cd ..

